### PR TITLE
changes as per amica

### PR DESCRIPTION
**Pull request by anuyabrahme**
**Please provide your name and company**

**Link the issue/feature request which this PR is meant to address**

**Detail what changes this PR introduces and how this addresses the issue/feature request linked above.**

**How did you validate the changes introduced within this PR?**

**Which warehouse did you use to develop these changes?**

**Did you update the CHANGELOG?**

- [ ] Yes

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)**

- [ ] Yes

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

**PR Template** 
- [Community Pull Request Template](?expand=1&template=pull_request_template.md) (default)

- [Maintainer Pull Request Template](?expand=1&template=maintainer_pull_request_template.md) (to be used by maintainers)

### CODE REVIEW

**Review by Sandeep-MBM — APPROVED** [review]
Looks Good

**Comment by fivetran-joemarkiewicz** [comment]
Hi @anuyabrahme and @Sandeep-MBM, it looks like this PR is being requested to be merged into the main repo. Were you planning to have these be merged into a fork instead?

**Comment by anuyabrahme** [comment]
yes, we want to merge in the forked

**Comment by fivetran-joemarkiewicz** [comment]
@anuyabrahme sounds good. If you want to merge this into your fork you'll want to adjust the base branch to be your fork instead of the main repo.

image

You should be able to do this by editing the base branch to be your repo:main.

**Comment by anuyabrahme** [comment]
thanks, when I edit this PR, I am not able to see the forked repo in the list.

**Comment by anuyabrahme** [comment]
Closing this PR as the destination branch should be the forked one.

**Pull request closed without merging**
