### PR TITLE
Bugfix/match type report adjustments

### PR DESCRIPTION
**Pull request by fivetran-joemarkiewicz**
**Are you a current Fivetran customer?** 

Fivetran created PR

**What change(s) does this PR introduce?** 

## 🪳 Bugfix 🪳
This PR includes the following bug fixes:
- In each end model, `*_id` fields are explicitly selected from the left side of the join, reports, rather than from entity (i.e. keywords) history tables. This is necessary as Microsoft **hard-deletes** records from history tables, and therefore, daily report fields may have `*_id` values that do not exist in history tables. ([#63](https://github.com/fivetran/dbt_ad_reporting/issues/63)).
- Includes the `match_type` field in the uniqueness test on the `microsoft_ads__search_report` model ([#64](https://github.com/fivetran/dbt_ad_reporting/issues/64)).

## Contributors:
- @clay-walker - Thank you for opening and providing information on issues [#63](https://github.com/fivetran/dbt_ad_reporting/issues/63) and [#64](https://github.com/fivetran/dbt_ad_reporting/issues/64)! 🎉 

**Did you update the CHANGELOG?** 

- [X] Yes

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [X] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [X] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [X] Yes, see the issue reference in the description
- [ ] No 

**How did you test the PR changes?** 

 

- [X] CircleCi  
- [X] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [X] BigQuery
- [X] Redshift
- [X] Snowflake
- [X] Postgres
- [X] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
🧉 

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

### CODE REVIEW

**Review by fivetran-jamie — APPROVED** [review]
LGTM! one q though - do we want to note that records with non-null _id fields and null _name fields reflect entities hard-deleted by microsoft? i suppose it's in the changelog, but maybe we wanna add it as well to the readme or decision log or something?

**Comment by fivetran-joemarkiewicz** [comment]
> LGTM! one q though - do we want to note that records with non-null _id fields and null _name fields reflect entities hard-deleted by microsoft? i suppose it's in the changelog, but maybe we wanna add it as well to the readme or decision log or something?

That's a great point. I will add a similar note from the CHANGELOG into the DECISIONLOG so it is not lost to time.

**Comment by fivetran-jamie** [comment]
ah .DS_Store snuck in there @fivetran-joemarkiewicz

**Comment by fivetran-joemarkiewicz** [comment]
> ah .DS_Store snuck in there @fivetran-joemarkiewicz

Ahhh good eye, just removed it.

**Pull request merged**
